POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDExNTA2NDksIm1vYmlsZSI6IjEzMzAwMDAxMTcxIiwiaWQiOjE3MjY1NzA3NTQ0NjU3MzA1NjAsImV4cCI6MTcwMTE5Mzg0OSwiaWF0IjoxNzAxMTUwNjQ5fQ.-UO0DCzjsf3eSlZg7ZIMsLZPdZTUszVP3ile72wzObA

{
  "dailyTrainTicketId": 1729414399258660864,
  "date": 1701273600000,
  "end": "宜兴站",
  "start": "南京站",
  "tickets": [
    {
      "passengerId": 1726877020044005376,
      "passengerIdCard": "123456789",
      "passengerName": "lxy",
      "passengerType": "2",
      "seatTypeCode": "1"
    }
  ],
  "trainCode": "D2"
}